---
title: 'Corona-Morphologie: Einfache Produktivitätsanalysen an konkreten Beispielen'
author: "Stefan Hartmann"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Literatur {-}
- Baayen, R. Harald. 1993. On Frequency, Transparency, and Productivity. In Geert E. Booij & Jaap van Marle (eds.), Yearbook of Morphology 1992, 181–208. Dordrecht: Kluwer.
- Baayen, R. Harald. 2009. Corpus Linguistics in Morphology: Morphological Productivity. In Anke Lüdeling & Merja Kytö (eds.), Corpus Linguistics, 899–919. Berlin, New York: De Gruyter.
- Baayen, Harald & Rochelle Lieber. 1991. Productivity and English Derivation: A Corpus-Based Study. Linguistics 29. 801–843.
- Barbaresi, Adrien. 2020. Coronakorpus. https://www.dwds.de/d/k-web#corona
- Bubenhofer, Noah. 2009. Sprachgebrauchsmuster. Korpuslinguistik als Methode der Diskurs- und Kulturanalyse. Berlin, Boston: de Gruyter.
- Gaeta, Livio & Davide Ricca. 2006. Productivity in Italian word-formation. Linguistics 44(1). 57–89.
- Gries, Stefan Th. & Anatol Stefanowitsch. 2004. Extending Collostructional Analysis: A Corpus-Based Perspective on “Alternations.” International Journal of Corpus Linguistics 9(1). 97–129.
- Hartmann, Stefan. 2016. Wortbildungswandel. Eine diachrone Studie zu deutschen Nominalisierungsmustern. Berlin, Boston: De Gruyter.
- Hartmann, Stefan. 2018. Derivational morphology in flux: a case study of word-formation change in German. Cognitive Linguistics 29(1). 77–119.
- Scherer, Carmen. 2006. Was ist Wortbildungswandel? Linguistische Berichte 205. 3–28.

