---
title: "Corona-Morphologie: Einfache Produktivitätsanalysen an konkreten Beispielen"
author: "Stefan Hartmann"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Einführung

Eine zentrale Frage insbesondere in der Wortbildungsforschung, aber auch in anderen Bereichen wie etwa der Syntax, lautet, in welchem Maße ein konkretes Muster in der Lage ist, Neubildungen hervorzubringen. Beispielsweise bringt das Suffix *-icht* (*Dickicht, Kehricht*) synchron gar keine Neubildungen mehr hervor, während etwa *-mäßig* relativ viele Neubildungen wie etwa *rezomäßig* hervorbringt. 

In diesem Tutorial kann ich zwar nicht auf komplexere Aspekte der Produktivitätsmessung eingehen, möchte aber zumindest einen groben Überblick über verbreitete Maße der morphologischen Produktivität geben und anhand eines konkreten Beispiels zeigen, wie sie sich operationalisieren lassen. Anschließend zeige ich noch, wie man mit Hilfe moderner Visualisierungsverfahren die Entstehung neuer Wörter quasi in Echtzeit verfolgen kann.

Wenn Sie die konkreten Anwendungsbeispiele selbst ausprobieren möchten, brauchen Sie für Kapitel 2 und 3 nur Excel oder ein anderes Tabellenkalkulationsprogramm wie LibreOffice Calc. Das vierte und fünfte Kapitel verwendet [R](https://r-project.org) und ist vermutlich eher für Fortgeschrittene interessant, die sich schon ein wenig mit R oder einer anderen Programmiersprache wie z.B. Python auskennen - alle anderen können versuchen, den konzeptionellen Ausführungen zu folgen, und/oder sich einfach die bunten Grafiken anschauen...

